import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<html lang="en" className="dark">
  <body className="bg-zinc-950 text-zinc-100 relative overflow-x-hidden">

    {/* BACKGROUND (DI BAWAH SEMUA) */}
    <div className="fixed inset-0 z-0 pointer-events-none" />

    {/* APP CONTENT */}
    <main className="relative z-10">
      {children}
    </main>

  </body>
</html>

  );
}
